# Docker Compose avec protection par mot de passe pour TransFlow
# Usage: docker-compose -f docker-compose.security.yml up -d

version: '3.8'

services:
  # Frontend avec protection par mot de passe
  transflow-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transflow-frontend-secure
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - VITE_APP_PASSWORD=${VITE_APP_PASSWORD:-TransFlow2024!}
    volumes:
      - ./nginx-auth.conf:/etc/nginx/conf.d/default.conf:ro
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - transflow-backend
    restart: unless-stopped
    networks:
      - transflow-network

  # Backend API
  transflow-backend:
    image: transflow-backend:latest
    container_name: transflow-backend-secure
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=production
      - PORT=5002
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - transflow-network

  # Base de données (optionnel)
  transflow-db:
    image: mysql:8.0
    container_name: transflow-db-secure
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-TransFlowDB2024!}
      MYSQL_DATABASE: transflow
      MYSQL_USER: transflow_user
      MYSQL_PASSWORD: ${DB_PASSWORD:-TransFlowUser2024!}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - transflow-network

  # Redis pour la gestion des sessions (optionnel)
  transflow-redis:
    image: redis:7-alpine
    container_name: transflow-redis-secure
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - transflow-network

  # Traefik pour le reverse proxy et HTTPS (optionnel)
  traefik:
    image: traefik:v2.10
    container_name: transflow-traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Dashboard Traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./certs:/certs
    restart: unless-stopped
    networks:
      - transflow-network
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL:-admin@transflow.local}"
      - "--certificatesresolvers.myresolver.acme.storage=/certs/acme.json"

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local

networks:
  transflow-network:
    driver: bridge

# Variables d'environnement à définir dans .env
# VITE_APP_PASSWORD=VotreMotDePasseSecurise123!
# DB_ROOT_PASSWORD=VotreMotDePasseDB2024!
# DB_PASSWORD=VotreMotDePasseUser2024!
# ACME_EMAIL=votre-email@domaine.com




