# Configuration Traefik pour TransFlow
# Gestion automatique des certificats SSL avec Let's Encrypt

api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true
  
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: transflow-network

certificatesResolvers:
  myresolver:
    acme:
      email: admin@transflow.local
      storage: /certs/acme.json
      httpChallenge:
        entryPoint: web

# Configuration des middlewares
http:
  middlewares:
    # Middleware de sécurité
    security-headers:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "strict-origin-when-cross-origin"
        contentSecurityPolicy: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:;"
    
    # Middleware de compression
    compress:
      compress: {}
    
    # Middleware de rate limiting
    rate-limit:
      rateLimit:
        burst: 100
        average: 50

# Configuration des logs
log:
  level: INFO
  format: json

accessLog:
  format: json
  fields:
    defaultMode: keep
    headers:
      defaultMode: keep




